(deftheme breeze-dark
  "An experimental theme to fit Emacs into Plasma")

(custom-theme-set-faces
 'breeze-dark
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#232629" :foreground "#cfcfc2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight medium :height 100 :width normal))))
 '(cursor ((t (:background "#cfcfc2"))))
 '(escape-glyph ((t (:foreground "#3daee9"))))
 '(homoglyph ((t (:foreground "#3daee9"))))
 '(minibuffer-prompt ((t (:inherit bold :foreground "#cfcfc2"))))
 '(highlight ((t (:background "#2d5c76" :foreground "#cfcfc2"))))
 '(region ((t (:extend t :background "#2d5c76"))))
 '(shadow ((t (:foreground "#7a7c7d"))))
 '(secondary-selection ((t (:extend t :background "#3f6caa"))))
 '(trailing-whitespace ((t (:background "#c0392b"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#cfcfc2" :weight bold))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:background "#232629" :foreground "#7a7c7d" :slant normal))))
 '(font-lock-constant-face ((t (:foreground "#27aeae"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#7a7c7d"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:inherit bold :foreground "#8e44ad"))))
 '(font-lock-keyword-face ((t (:inherit bold :foreground "#cfcfc2" :slant normal :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#da4453"))))
 '(font-lock-number-face ((t (:foreground "#f67400"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#27ae60"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#3f8058"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#f44f4f"))))
 '(font-lock-type-face ((t (:inherit nil :foreground "#2980b9"))))
 '(font-lock-variable-name-face ((t (:foreground "#27aeae"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:background "#4d1f24" :foreground "#95da4c"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline t))))
 '(link-visited ((t (:underline t))))
 '(fringe ((t nil)))
 '(header-line ((t (:background "#cfcfc2" :weight bold))))
 '(tooltip ((t (:background "#232629" :foreground "#cfcfc2" :underline nil :slant normal :weight normal))))
 '(mode-line ((t (:background "#232629" :foreground "#cfcfc2" :box (:line-width (1 . 1) :color "#3daee9")))))
 '(mode-line-buffer-id ((t (:inherit bold :foreground "#3daee9"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#3daee9" :style released-button)))))
 '(mode-line-inactive ((t (:background "#31363b" :foreground "#425558" :box (:line-width (1 . 1) :color "#5f6265")))))
 '(isearch ((t (:background "#218058" :foreground "#cfcfc2"))))
 '(isearch-fail ((t (:background "#da4453"))))
 '(lazy-highlight ((t (:background "#808021" :weight normal))))
 '(match ((t (:background "#444155" :foreground "#86dc2f"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit isearch)))))

(provide-theme 'breeze-dark)
